# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   eyaml edit --pkcs7-private-key=/keybase/team/epfl_lil/eyaml/private_key.pkcs7.pem --pkcs7-public-key /keybase/team/epfl_lil/eyaml/public_key.pkcs7.pem roles/lil-namespace/vars/quay-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: "{{ playbook_dir }}/eyaml/private_key.pkcs7.pem"
  pub: "{{ playbook_dir }}/eyaml/public_key.pkcs7.pem"

quay:
  # To regenerate this token:
  # (paraphrased from https://docs.redhat.com/en/documentation/red_hat_quay/3/html-single/red_hat_quay_api_guide/index#token-overview)
  #
  # 1. Browse https://quay-its.epfl.ch/
  # 2. **Make sure to log out and then back in.** Some token manipulation steps require either
  #    that you have a fresh (less than a few minutes old) session, or that you type in your
  #    password to re-autenticate. Unfortunately the latter will *not* work on quay-its.epfl.ch,
  #    no matter what. (Mumble LDAP something something)
  # 3. Browse https://quay-its.epfl.ch/organization/svc0187?tab=OAuthApplications
  # 4. (If not already done) Create the `ansible` application. Click the “Create New Application” button in the upper right corner; type in ansible and press Enter.
  #
  #    💡 If you get prompted for a password at this time, it means that you didn't read
  #    the above instructions carefully. Sorry about that.
  # 5. Click the `ansible` hyperlink
  # 6. Click Generate Token (pictured by a cinema ticket)- in the left sidebar
  # 7. Check the “Administer Organization”, “Administer Repositories” and “Create Repositories” boxes
  #    and leave all others unchecked.
  # 8. Click the Generate Access Token button (green) at the bottom
  # 9. Click Authorize application
  # 10. A token should appear. If it doesn't, see 💡, above.
  org_admin_token: ENC[PKCS7,MIIB4wYJKoZIhvcNAQcDoIIB1DCCAdACAQAxggFrMIIBZwIBADBPMEIxQDA+BgNVBAMMN0VZQU1MIHByb2R1Y3Rpb24gc2VjcmV0cyBmb3IgdGhlIExIRC9DYXRhbHlzZSBlY29zeXN0ZW0CCQDJ+75heGUgjjANBgkqhkiG9w0BAQEFAASCAQCvQaCXyV6k1Y6XJZKUZVvyps8BSS47keNDtjRXzWo6rA7QVyiBoFn67K8ZMq5fP/CJHZ31BkcqnTHxtWxi1FfzEscJRE1ymlVLBJXt9DsnZWY4jaIFJfDHoPGVxONSq1Qrz5u+1xkD1dutdLID/nTx9zuRaPNCeRKMqVd/pHj5m1n8VC5NBRPEMNE3qWjSXJ7PU0PQ/EZBWZWyV493Gr6cchCMLJCyFFdmeY4TdSLZe3IcabolvuTcexvXsl8GBJmwlWNtlDb2AN6Fh8EgQkYbasIseNNeIoEtwMAtDQ94RV076V37KF4GBqrlNQrwfVVOeQKRm9sGl3GSkF9NweTgMFwGCSqGSIb3DQEHATAdBglghkgBZQMEASoEEEUVH9RB4uegHzurKghIOSyAMPXp+JmDKWJ7Tb/bJ7rqTEyUj95LLGlXiHpJ981PBIWA+ZSeTbARfhaAHmWAnHdtDA==]
